/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene-processed.gltf
Author: ANdrewsss (https://sketchfab.com/ANdrewsss)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone13-expectation-navy-color-179bcca3f7674e8282bdc19e621bd38d
Title: iPhone13 expectation Navy color
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-processed.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.07, 0]} scale={3}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.Shutter} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.line} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.gls2} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.Shutter} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.Shutter} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_96.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_102.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Object_108.geometry} material={materials.lambert1} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene-processed.gltf')
